version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/elixir/dialyzer"
      - "/elixir/setup"
      - "/nodejs/setup"
      - "/semantic-pull-request"
      - "/stale"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 3
