name: Elixir Setup
description: Set up the Elixir environment
author: Straw Hat Team

inputs:
  elixir-version:
    description: The Elixir version. It fallback to .tool-versions if not specified
    required: false
  otp-version:
    description: The Erlang version. It fallback to .tool-versions if not specified
    required: false
  version-type:
    description: The versioning type check, either strict or loose
    required: false
    default: strict

outputs:
  elixir-version:
    description: The resolved Elixir version
    value: ${{ steps.setup-beam.outputs.elixir-version }}
  otp-version:
    description: The resolved OTP version
    value: ${{ steps.setup-beam.outputs.otp-version }}

runs:
  using: composite
  steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      id: setup-beam
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        version-type: ${{ inputs.version-type }}
        version-file: .tool-versions

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      shell: sh
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
