name: Elixir Setup
description: Set up the Elixir environment
author: Straw Hat Team

inputs:
  elixir-version:
    description: The Elixir version. It fallback to .tool-versions if not specified
    required: false
  otp-version:
    description: The Erlang version. It fallback to .tool-versions if not specified
    required: false
  version-type:
    description: The versioning type check, either strict or loose
    required: false
    default: strict

runs:
  using: composite
  steps:
    - name: Reading Elixir version from .tool-versions
      id: tool-versions-elixir
      uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.7.5
      with:
        plugin-name: elixir
      if: ${{ ! inputs.elixir-version }}

    - name: Reading Erlang version from .tool-versions
      id: tool-versions-erlang
      uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.7.5
      with:
        plugin-name: erlang
      if: ${{ ! inputs.otp-version }}

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ inputs.elixir-version || steps.tool-versions-elixir.outputs.plugin-version }}
        otp-version: ${{ inputs.otp-version || steps.tool-versions-erlang.outputs.plugin-version }}
        version-type: ${{ inputs.version-type }}

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      shell: sh
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
