name: NodeJS Prettier
description: Run the prettier formatter
author: Straw Hat Team

inputs:
  sht-npm-token:
    description: The Straw Hat NPM Token that may be injected into the .yarnrc.yml file
    required: false

runs:
  using: composite
  steps:
    - shell: sh
      run: yarn prettier --check */** --ignore-unknown --no-error-on-unmatched-pattern
      env:
        SHT_NPM_TOKEN: ${{ inputs.sht-npm-token }}
