name: NodeJS Prettier
description: Run the prettier formatter
author: Straw Hat Team

runs:
  using: composite
  steps:
    - shell: sh
      run: yarn prettier --check */** --ignore-unknown --no-error-on-unmatched-pattern
