name: Stale
description: Warns and then closes issues and PRs that have had no activity for a specified amount of time
author: Straw Hat Team

runs:
  using: composite
  steps:
    - name: Check stale issues and pull requests
      uses: actions/stale@v8
      with:
        days-before-issue-stale: 30
        days-before-issue-close: 15
        days-before-pr-stale: 60
        days-before-pr-close: 60

        stale-issue-label: 'stale:discard'
        exempt-issue-labels: 'stale:keep'
        stale-issue-message: >
          This issue has been automatically marked as `stale:discard`. **If this issue still relevant, please leave
          any comment** (for example, "bump"), and we'll keep it open. We are sorry that we haven't been able to
          prioritize it yet.
          If you have any new additional information, please include it with your comment.
        close-issue-message: >
          Closing this issue after a prolonged period of inactivity. If this issue is still relevant, feel free to
          re-open the issue. Thank you!

        stale-pr-label: 'stale:discard'
        exempt-pr-labels: 'stale:keep'
        stale-pr-message: >
          This pull request has been automatically marked as `stale:discard`. **If this pull request is still
          relevant, please leave any comment** (for example, "bump"), and we'll keep it open. We are sorry that we
          haven't been able to prioritize reviewing it yet.
          Your contribution is very much appreciated!.
        close-pr-message: >
          Closing this pull request after a prolonged period of inactivity. If this issue is still relevant, please
          ask for this pull request to be reopened. Thank you!
