name: Elixir Dialyzer
description: Runs Dialyxir typespec analysis
author: Straw Hat Team

inputs:
  elixir-version:
    description: The Elixir version. It fallback to .tool-versions if not specified
    required: false
  otp-version:
    description: The Erlang version. It fallback to .tool-versions if not specified
    required: false
  version-type:
    description: The versioning type check, either strict or loose
    required: false
    default: strict

runs:
  using: composite
  steps:
    - name: Setup Elixir
      uses: straw-hat-team/github-actions-workflows/elixir/setup@v1.7.7
      id: beam
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        version-type: ${{ inputs.version-type }}

    - name: Restore PLT cache
      uses: actions/cache/restore@v4
      id: plt_cache
      with:
        key: |
          ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
        restore-keys: |
          ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
        path: |
          priv/plts

    - name: Create PLTs
      shell: sh
      if: steps.plt_cache.outputs.cache-hit != 'true'
      run: mix dialyzer --plt

    - name: Save PLT cache
      uses: actions/cache/save@v4
      if: steps.plt_cache.outputs.cache-hit != 'true'
      id: plt_cache_save
      with:
        key: |
          ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
        path: |
          priv/plts

    - name: Run dialyzer
      shell: sh
      run: mix dialyzer --format github
