name: Elixir Compilation Warnings
description: Checks for compilation warnings
author: Straw Hat Team

inputs:
  elixir-version:
    description: The Elixir version. It fallback to .tool-versions if not specified
    required: false
  otp-version:
    description: The Erlang version. It fallback to .tool-versions if not specified
    required: false
  version-type:
    description: The versioning type check, either strict or loose
    required: false
    default: strict

runs:
  using: composite
  steps:
    - name: Setup Elixir
      uses: straw-hat-team/github-actions-workflows/elixir/setup@v1.7.5
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}
        version-type: ${{ inputs.version-type }}

    - name: Run compilation
      shell: sh
      run: mix compile --warnings-as-errors --force
