name: Git Set SHT Bot User
description: Set the git user for the repository using Straw Hat Team bot account
author: Straw Hat Team

runs:
  using: composite
  steps:
    - name: Set Git User
      shell: bash
      run: |
        git config --global user.name sht-bot
        git config --global user.email opensource+sht-bot@straw-hat-llc.com
