on:
  workflow_call:
    inputs:
      elixir-version:
        description: The Elixir version. It fallsback to .tool-versions if not specified
        type: string
        required: false
      otp-version:
        description: The Erlang version. It fallsback to .tool-versions if not specified
        type: string
        required: false
      testing-enabled:
        description: Enables the testing job
        type: boolean
        required: false
        default: true
      formatter-enabled:
        description: Enables the formatter job
        type: boolean
        required: false
        default: true
      credo-enabled:
        description: Enables the linter job
        type: boolean
        required: false
        default: true
      dialyzer-enabled:
        description: Enables the typespec job
        type: boolean
        required: false
        default: true

jobs:
  test:
    name: Test
    if: ${{ inputs.testing-enabled }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: straw-hat-team/github-actions-workflows/elixir/test@testing-elixir
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}

  format:
    name: Format
    if: ${{ inputs.formatter-enabled }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: straw-hat-team/github-actions-workflows/elixir/format@testing-elixir
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}

  credo:
    name: Credo
    if: ${{ inputs.credo-enabled }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: straw-hat-team/github-actions-workflows/elixir/credo@testing-elixir
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}

  dialyzer:
    name: Dialyzer
    if: ${{ inputs.dialyzer-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: straw-hat-team/github-actions-workflows/elixir/dialyzer@testing-elixir
        with:
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}
