on:
  workflow_call:
    inputs:
      jest-enabled:
        description: Enables the Jest testing job
        type: boolean
        required: false
        default: true
      prettier-enabled:
        description: Enables the Prettier formatter job
        type: boolean
        required: false
        default: true
    secrets:
      SHT_NPM_TOKEN:
        description: The Straw Hat NPM Token that may be injected into the .yarnrc.yml file
        required: false

jobs:
  jest:
    name: Jest
    if: ${{ inputs.jest-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.3.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/jest@v1.3.0

  prettier:
    name: Prettier
    if: ${{ inputs.prettier-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.3.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/prettier@v1.3.0
