on:
  workflow_call:
    inputs:
      sht-npm-token:
        description: The Straw Hat NPM Token that may be injected into the .yarnrc.yml file
        type: string
        required: false
      jest-enabled:
        description: Enables the Jest testing job
        type: boolean
        required: false
        default: true
      prettier-enabled:
        description: Enables the Prettier formatter job
        type: boolean
        required: false
        default: true

jobs:
  jest:
    name: Jest
    if: ${{ inputs.jest-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.3.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ inputs.sht-npm-token }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/jest@v1.3.0

  prettier:
    name: Prettier
    if: ${{ inputs.prettier-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.3.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ inputs.sht-npm-token }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/prettier@v1.3.0
