on:
  workflow_call:
    inputs:
      jest-enabled:
        description: Enables the Jest testing job
        type: boolean
        required: false
        default: true
      prettier-enabled:
        description: Enables the Prettier formatter job
        type: boolean
        required: false
        default: true
    secrets:
      SHT_NPM_TOKEN:
        description: The Straw Hat NPM Token that may be injected into the .yarnrc.yml file
        required: false

jobs:
  jest:
    name: Jest
    if: ${{ inputs.jest-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@0566a3861e8d30656cd902efd6208247df46bf60 # v1.8.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/jest@0566a3861e8d30656cd902efd6208247df46bf60 # v1.8.0
        with:
          sht-npm-token: ${{ secrets.SHT_NPM_TOKEN }}

  prettier:
    name: Prettier
    if: ${{ inputs.prettier-enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@0566a3861e8d30656cd902efd6208247df46bf60 # v1.8.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/prettier@0566a3861e8d30656cd902efd6208247df46bf60 # v1.8.0
        with:
          sht-npm-token: ${{ secrets.SHT_NPM_TOKEN }}
