name: ASDF Get Version
description: Returns the version of the plugin from .tool-versions file managed by asdf
author: Straw Hat Team

inputs:
  plugin-name:
    description: The name of the plugin you want to get the version of
    required: true

outputs:
  plugin-version:
    description: "The version of the plugin"
    value: ${{ steps.get-version.outputs.plugin-version }}

runs:
  using: composite
  steps:
    - id: get-version
      shell: sh
      run: |
        echo "::set-output name=plugin-version::$(awk '/${{ inputs.plugin-name }}/ { print $2 }' .tool-versions)"
    - shell: sh
      run: |
        echo "\033[0;31m'${{ inputs.plugin-name }}' version not found. Make sure that .tool-versions exists and '${{ inputs.plugin-name }}' version is specified in it"
        exit 1
      if: ${{ steps.get-version.outputs.plugin-version }} == ""
