name: Semantic Pull Request
description: Ensures that the Pull Request title matches Conventional Commits spec
author: Straw Hat Team

inputs:
  github-token:
    description: The Github API token.
    required: true
  require-scope:
    description: Configure that a scope must always be provided.
    required: false
    default: 'false'
  scopes:
    description: Configure which scopes are allowed.
    required: false

runs:
  using: composite
  steps:
    - name: Check Pull Request Title
      id: lint_pr_title
      uses: amannn/action-semantic-pull-request@v5.4.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        types: |
          feat
          fix
          refactor
          chore
          revert
        requireScope: ${{ inputs.require-scope }}
        scopes: ${{ inputs.scopes }}
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.
        wip: true
        validateSingleCommit: true
    - uses: marocchino/sticky-pull-request-comment@v2.9.0
      if: always() && (steps.lint_pr_title.outputs.error_message != null)
      with:
        header: pr-title-lint-error
        message: |
          We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
          to ensure that the versioning of the project is done correctly.

          ### Supported Types

          - feat: A new feature, resulting in a MINOR version bump.
          - fix: A bug fix, resulting in a PATCH version bump.
          - refactor: A code change that neither fixes a bug nor adds a feature, resulting in a PATCH version bump.
          - chore: Changes unrelated to the release code, resulting in no version bump.
          - revert: Reverts a previous commit.

          ### Details:

          ```
          ${{ steps.lint_pr_title.outputs.error_message }}
          ```
    - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
      uses: marocchino/sticky-pull-request-comment@v2.9.0
      with:
        header: pr-title-lint-error
        delete: true
