name: Semantic Pull Request
description: Ensures that the Pull Request title matches Conventional Commits spec
author: Straw Hat Team

inputs:
  github-token:
    description: The Github API token.
    required: true

runs:
  using: composite
  steps:
    - name: Check Pull Request Title
      uses: amannn/action-semantic-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        types: |
          fix
          feat
          chore
        requireScope: false
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.
        wip: true
        validateSingleCommit: true
